Fix: use PROJECT_TRYPE to get the store file path
raxjs/rax-app pull request #768
Opened 2021-07-07 04:23 UTC by luhc228

2021-07-07 08:34 UTC, SoloJiang commented on packages/plugin-rax-store/src/utils/getStoreFileType.ts
> +  const matchingPaths = globby.sync('store.*', { cwd: dirPath });
一个带了后缀名，一个没带？

2021-07-07 08:34 UTC, SoloJiang commented on packages/plugin-rax-store/src/utils/getStoreFileType.ts
> +}
1. 这里抛错是不是不太好？我看到你用的地方都 try catch 了
2. 这里用 globby，是不是还不如 `fs.existsSync` 简单

2021-07-07 09:08 UTC, ClarkXia commented on packages/codemod/src/hooks/app.ts
> +    const pkgJSON = JSON.parse(fs.readFileSync(path.join(rootDir, 'package.json'), 'utf8'));
fs.readJsonSync ?

2021-07-07 09:08 UTC, ClarkXia commented on packages/plugin-rax-store/src/utils/modifyRoutes.ts
> +    getPageStorePath(srcPath, pageName);
getXxx 没有返回值？为什么是一个 try catch 逻辑

2021-07-07 12:51 UTC, luhc228 commented on packages/plugin-rax-store/src/utils/modifyRoutes.ts
> +    getPageStorePath(srcPath, pageName);
fixed. 不用 try catch 逻辑了

2021-07-07 12:51 UTC, luhc228 commented on packages/plugin-rax-store/src/utils/getStoreFileType.ts
> +  const matchingPaths = globby.sync('store.*', { cwd: dirPath });
fixed

2021-07-07 12:51 UTC, luhc228 commented on packages/codemod/src/hooks/app.ts
> +    const pkgJSON = JSON.parse(fs.readFileSync(path.join(rootDir, 'package.json'), 'utf8'));
done

2021-07-07 12:51 UTC, luhc228 commented on packages/plugin-rax-store/src/utils/getStoreFileType.ts
> +}
fixed

2021-07-08 02:26 UTC, SoloJiang approved these changes

2021-07-08 06:03 UTC, ClarkXia requested changes

2021-07-08 06:03 UTC, ClarkXia commented on packages/codemod/src/hooks/app.ts
> +    const pkgJSON = JSON.parse(fs.readJSONSync(path.join(rootDir, 'package.json')));
fs.readJSONSync 返回的应该就是 object

2021-07-08 06:44 UTC, ClarkXia approved these changes

2021-07-08 07:14 UTC, merged